FROM ahmadiq/tomcat:8

RUN rm -f /etc/service/sshd/down

#Tomcat location
WORKDIR /tomcat

RUN rm -Rf webapps/*
ADD *.war webapps/ROOT.war

EXPOSE 8080
# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]